
name: Lint and Test

on:
  push:
    paths:
      - ".github/**/*"
      - "archivebot/**"
  pull_request:
    paths:
      - ".github/**/*"
      - "archivebot/**"

defaults:
  run:
    working-directory: archivebot

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Lint code
        run: |
          poetry run just lint

      - name: Run tests
        run: |
          poetry run just test
